language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
  licenses:
    - 'android.*'

script: ./gradlew clean build --info --stacktrace

sudo: false

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
