language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
  licenses:
    - 'android.*'

script: ./gradlew clean build --info --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
